#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CLOCK_SAMPLE_TIME 0.001

#define CONTROLLER_SAMPLE_TIME 0.001
#define CONTROLLER_MAX_COUNTER CONTROLLER_SAMPLE_TIME / CLOCK_SAMPLE_TIME

#define ENCODER_RESOLUTION 360

#define ROBOT_RADIUS 19

#define PI 3.14159265
#define RADIAN_PROP PI / 180
#define DEGREE_PROP 180 / PI

#define MAX_ANGULAR_VELOCITY 6.15       // [rad/s]
#define ROBOT_DIAMATER_CM 38            // [cm]
#define WHEEL_DIAMATER_M 0.065          // [m]

#define SIMULATION_SAMPLE_TIME 0.004    // [s]
#define SIMULATION_MAX_COUNTER (int)((SIMULATION_SAMPLE_TIME / CLOCK_SAMPLE_TIME) / 2)

#define MAX_NUMBERS_OF_GARBAGES_IN_ROOM 5

#endif // CONSTANTS_H